name: Deploy Telegram Bot

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npx prisma generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Run database migrations
      run: |
        echo "Проверяем состояние миграций..."
        npx prisma migrate status || echo "Миграции не применены"
        echo "Пропускаем миграции для существующей БД"
        echo "Миграции будут применены на сервере при необходимости"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BOT_HOST }}
        username: ${{ secrets.BOT_USERNAME }}
        key: ${{ secrets.BOT_SSH_KEY }}
        port: ${{ secrets.BOT_SSH_PORT || 22 }}
        script: |
          # Проверяем переменные окружения
          echo "🔍 Проверяем переменные..."
          echo "BOT_DEPLOY_PATH: ${{ secrets.BOT_DEPLOY_PATH }}"
          echo "Текущая директория: $(pwd)"
          
          # Проверяем, существует ли директория
          if [ ! -d "${{ secrets.BOT_DEPLOY_PATH }}" ]; then
            echo "❌ Директория ${{ secrets.BOT_DEPLOY_PATH }} не существует!"
            echo "📁 Создаем директорию..."
            sudo mkdir -p ${{ secrets.BOT_DEPLOY_PATH }}
            sudo chown $USER:$USER ${{ secrets.BOT_DEPLOY_PATH }}
          fi
          
          # Переходим в директорию бота
          cd ${{ secrets.BOT_DEPLOY_PATH }}
          echo "📂 Перешли в директорию: $(pwd)"
          
          # Проверяем, клонирован ли репозиторий
          if [ ! -d ".git" ]; then
            echo "📥 Клонируем репозиторий..."
            git clone https://github.com/jes11sy/botdir.git .
          fi
          
          # Проверяем установку Node.js и PM2
          echo "🔧 Проверяем зависимости..."
          node --version || echo "❌ Node.js не установлен"
          npm --version || echo "❌ npm не установлен"
          pm2 --version || echo "❌ PM2 не установлен"
          
          # Останавливаем бота (если запущен)
          pm2 stop bot || echo "Бот не был запущен"
          pm2 stop webhook || echo "Webhook не был запущен"
          
          # Обновляем код
          echo "📥 Обновляем код..."
          git pull origin main
          
          # Устанавливаем зависимости
          echo "📦 Устанавливаем зависимости..."
          npm ci --production
          
          # Генерируем Prisma клиент
          echo "🔧 Генерируем Prisma клиент..."
          npx prisma generate
          
          # Применяем миграции (если нужно)
          echo "🗄️ Проверяем миграции..."
          npx prisma migrate status || {
            echo "Создаем baseline для существующей БД..."
            npx prisma migrate resolve --applied "20250920143952_add_today_stats_to_avito" || true
            npx prisma migrate resolve --applied "20250923071207_add_master_change_field" || true
            npx prisma migrate resolve --applied "20250923071427_recreate_database" || true
            npx prisma migrate resolve --applied "add_city_to_cash" || true
            npx prisma migrate resolve --applied "add_master_change_manual" || true
            npx prisma migrate resolve --applied "add_tg_id_chat_id_to_master" || true
            npx prisma migrate resolve --applied "add_tg_id_to_director" || true
          }
          npx prisma migrate deploy
          
          # Запускаем бота
          echo "🚀 Запускаем бота..."
          pm2 start ecosystem.config.js --env production
          
          # Сохраняем конфигурацию PM2
          pm2 save
          
          # Показываем статус
          echo "📊 Статус процессов:"
          pm2 status
